stages:
  - build
  - deploy

build-docker:
  stage: build
  image: docker:20.10.22-dind
  services: 
    - docker:dind
  tags:
    - dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE
deploy-docker:
  before_script:
    - docker context create --docker "host=$DOCKER_HOST" 
    - docker context use $DOCKER_CONTEXT
  stage: deploy
  image: docker:20.10.22-dind
  services: 
    - docker:dind
  tags:
    - dind
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker stop app || true
    - docker rm app || true
    - docker run --name app -p 8000:80  $CI_REGISTRY_IMAGE
