stages:
  - build
  - deploy

build-docker:
  stage: build
  image: docker:20.10.22-dind
  services: 
    - docker:dind
  tags:
    - dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:latest services/app
    - docker push $CI_REGISTRY_IMAGE
  only:
    changes:
      - services/app/**/
    refs:
      - master
deploy-docker:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  stage: deploy
  image: docker:20.10.22-dind
  services: 
    - docker:dind
  tags:
    - dind

  script:
    - DOCKER_HOST=ssh://$DEPLOY_HOST docker pull $CI_REGISTRY_IMAGE
    - DOCKER_HOST=ssh://$DEPLOY_HOST docker stop app || true
    - DOCKER_HOST=ssh://$DEPLOY_HOST docker rm app || true
    - DOCKER_HOST=ssh://$DEPLOY_HOST docker run --name app -p 8000:80  $CI_REGISTRY_IMAGE
