version: "3.10"
volumes:
  #This stores the state of openbis, including logs
  openbis-state:
  certs:
  db_data: null
  worker_dependency_cache: null
networks:
  local:
    driver: bridge
    driver_opts:
      subnet: "192.168.0.0/24"




services:
  #Openbis
  openbis:
    image: openbis/debian-openbis:latest
    env_file:
      - ./.env

    environment:
      #Here you can configure some openbis options for the AS
      - SERVER_HOST_PORT=localhost:8443
      - GROUP_ID=1000
      #Enable the basic plugins
      - CORE_PLUGINS=enabled-modules = dataset-uploader, dataset-file-search, xls-import, eln-lims, openbis-ng-ui, search-store, user-management-maintenance
    volumes:
      - openbis-state:/home/openbis/openbis_state/
      - certs:/home/openbis/openbis_state/cert/
    ports:
      - ${OPENBIS_PORT}:443
    
    hostname: openbis
    healthcheck:
      test: [ "CMD", "curl", "openbis:443" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - local
  app:
    env_file:
      - ./.env
    build:
      context: ./services/app
      dockerfile: Dockerfile
    # volumes:
    #   - ./services/app/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - local
    ports:
      - ${CADDY_PORT}:80
    hostname: openbischef.scit.empa.ch


    

