import fs from 'fs/promises';

// Define the list of names
const names = [
    "AuthorizationGroup",
    "AuthorizationGroupCreation",
    "AuthorizationGroupDeletionOptions",
    "AuthorizationGroupFetchOptions",
    "AuthorizationGroupPermId",
    "AuthorizationGroupSearchCriteria",
    "AuthorizationGroupUpdate",
    "CreateAuthorizationGroupsOperation",
    "CreateDataSetTypesOperation",
    "CreateExperimentTypesOperation",
    "CreateMaterialTypesOperation",
    "CreatePersonsOperation",
    "CreatePluginsOperation",
    "CreatePropertyTypesOperation",
    "CreateQueriesOperation",
    "CreateRoleAssignmentsOperation",
    "CreateSampleTypesOperation",
    "CreateVocabulariesOperation",
    "CreateVocabularyTermsOperation",
    "CustomASServiceCode",
    "CustomASServiceExecutionOptions",
    "DataSetFetchOptions",
    "DataSetPermId",
    "DataSetSearchCriteria",
    "DataSetType",
    "DataSetTypeCreation",
    "DataSetTypeDeletionOptions",
    "DataSetTypeFetchOptions",
    "DataSetTypeSearchCriteria",
    "DataSetTypeUpdate",
    "DataType",
    "DeleteAuthorizationGroupsOperation",
    "DeleteDataSetTypesOperation",
    "DeleteExperimentTypesOperation",
    "DeleteMaterialTypesOperation",
    "DeletePersonsOperation",
    "DeletePluginsOperation",
    "DeletePropertyTypesOperation",
    "DeleteQueriesOperation",
    "DeleteRoleAssignmentsOperation",
    "DeleteSampleTypesOperation",
    "DeleteVocabulariesOperation",
    "DeleteVocabularyTermsOperation",
    "DynamicPropertyPluginEvaluationResult",
    "EntityValidationPluginEvaluationResult",
    "EntityKind",
    "EntityTypePermId",
    "EventType",
    "ExperimentFetchOptions",
    "ExperimentIdentifier",
    "ExperimentSearchCriteria",
    "ExperimentType",
    "ExperimentTypeCreation",
    "ExperimentTypeDeletionOptions",
    "ExperimentTypeFetchOptions",
    "ExperimentTypeSearchCriteria",
    "ExperimentTypeUpdate",
    "MaterialFetchOptions",
    "MaterialPermId",
    "MaterialSearchCriteria",
    "MaterialType",
    "MaterialTypeCreation",
    "MaterialTypeDeletionOptions",
    "MaterialTypeFetchOptions",
    "MaterialTypeSearchCriteria",
    "MaterialTypeUpdate",
    "Me",
    "Person",
    "PersonCreation",
    "PersonDeletionOptions",
    "PersonFetchOptions",
    "PersonPermId",
    "PersonSearchCriteria",
    "PersonUpdate",
    "PersonalAccessTokenSearchCriteria",
    "PersonalAccessTokenFetchOptions",
    "Plugin",
    "PluginCreation",
    "PluginDeletionOptions",
    "PluginFetchOptions",
    "PluginEvaluationOptions",
    "EntityValidationPluginEvaluationOptions",
    "DynamicPropertyPluginEvaluationOptions",
    "PluginKind",
    "PluginPermId",
    "PluginSearchCriteria",
    "PluginType",
    "PluginUpdate",
    "Project",
    "ProjectFetchOptions",
    "ProjectIdentifier",
    "ProjectSearchCriteria",
    "PropertyAssignment",
    "PropertyAssignmentCreation",
    "PropertyAssignmentFetchOptions",
    "PropertyAssignmentPermId",
    "PropertyAssignmentSearchCriteria",
    "PropertyType",
    "PropertyTypeCreation",
    "PropertyTypeDeletionOptions",
    "PropertyTypeFetchOptions",
    "PropertyTypePermId",
    "PropertyTypeSearchCriteria",
    "PropertyTypeUpdate",
    "Query",
    "QueryCreation",
    "QueryDatabase",
    "QueryDatabaseName",
    "QueryDeletionOptions",
    "QueryExecutionOptions",
    "SqlExecutionOptions",
    "QueryFetchOptions",
    "QueryDatabaseFetchOptions",
    "QueryName",
    "QuerySearchCriteria",
    "QueryDatabaseSearchCriteria",
    "QueryTechId",
    "QueryType",
    "QueryUpdate",
    "Role",
    "RoleAssignment",
    "RoleAssignmentCreation",
    "RoleAssignmentDeletionOptions",
    "RoleAssignmentTechId",
    "RoleLevel",
    "SampleFetchOptions",
    "SampleIdentifier",
    "SampleSearchCriteria",
    "SampleType",
    "SampleTypeCreation",
    "SampleTypeDeletionOptions",
    "SampleTypeFetchOptions",
    "SampleTypeSearchCriteria",
    "SampleTypeUpdate",
    "SearchDataSetsOperation",
    "SearchExperimentsOperation",
    "SearchMaterialsOperation",
    "SearchResult",
    "SearchSamplesOperation",
    "Space",
    "SpaceFetchOptions",
    "SpacePermId",
    "SpaceSearchCriteria",
    "SynchronousOperationExecutionOptions",
    "TableModel",
    "TableColumn",
    "TableStringCell",
    "UpdateAuthorizationGroupsOperation",
    "UpdateDataSetTypesOperation",
    "UpdateExperimentTypesOperation",
    "UpdateMaterialTypesOperation",
    "UpdatePersonsOperation",
    "UpdatePluginsOperation",
    "UpdatePropertyTypesOperation",
    "UpdateQueriesOperation",
    "UpdateSampleTypesOperation",
    "UpdateVocabulariesOperation",
    "UpdateVocabularyTermsOperation",
    "Vocabulary",
    "VocabularyCreation",
    "VocabularyDeletionOptions",
    "VocabularyFetchOptions",
    "VocabularyPermId",
    "VocabularySearchCriteria",
    "VocabularyTerm",
    "VocabularyTermCreation",
    "VocabularyTermDeletionOptions",
    "VocabularyTermFetchOptions",
    "VocabularyTermPermId",
    "VocabularyTermSearchCriteria",
    "VocabularyTermUpdate",
    "VocabularyUpdate",
    "WebAppSettingCreation",
    "WebAppSettings",
    "WebAppSetting"
];



// Output file
const outputFilePath = 'dto.js';





const newNames = names.map(name => [name, `${name}Dto`]);

const exports = newNames.map(([name, dtoName]) => {
    return [name, dtoName, `const ${dtoName} = V3API.${name};`]
})


const allImports = exports.map(([name, dtoName, importStatement]) => importStatement).join('\n')

const allExports = exports.map(([name, dtoName, exportStatement]) => {
    return `${dtoName} as ${name}`
}).join(',\n')


const constOut = `// Auto-generated file\nimport V3API from 'v3api/V3API.esm';\n${allImports}\n\nexport {\n${allExports}\n}\n`

console.log(constOut)
console.log(`Generated ${outputFilePath}`);

// Start writing to the output file
await fs.writeFile(outputFilePath, constOut);