import { Metagraph } from "../metagraph/metagraph";

export const polyproWorkflow = new Metagraph(
    [
      {
        id: "Select extruder",
        collection: "/POLPRO_EQUIPMENT/EXTRUSION/EXTRUSION_EXP_1",
        type: "select",
        entityType: "EXTRUDER",
        dependencies: [],
        description: "Select the extruder",
      },
      {
        id: "Extruder Parameter",
        collection: "/POLPRO_RUDOLF.HUFENUS_AT_EMPA.CH/TEST/TEST_EXP_1",
        type: "entry",
        entityType: "PARAMETER_EXTRUDER",
        dependencies: ["Select extruder"],
        description: "Enter the parameters for the extruder",
      },
      {
        id: "Select spin pack",
        collection: "/POLPRO_EQUIPMENT/EXTRUSION/EXTRUDER_EXP_8",
        type: "select",
        entityType: "SPIN_PACK",
        dependencies: [],
        description: "Select the spin pack",
      },
      {
        id: "Spin pack parameter",
        collection: "/POLPRO_RUDOLF.HUFENUS_AT_EMPA.CH/TEST/TEST_EXP_1",
        type: "entry",
        entityType: "PARAMETER_SPIN_PACK",
        dependencies: ["Select spin pack"],
        description: "Enter the parameters for the spin pack",
      },
      {
        id: "Select die",
        collection: "/POLPRO_EQUIPMENT/EXTRUSION/EXTRUDER_EXP_2",
        type: "select",
        entityType: "DIES",
        dependencies: [],
        description: "Select the die",
      },
      {
        id: "Die parameter",
        collection: "/POLPRO_RUDOLF.HUFENUS_AT_EMPA.CH/TEST/TEST_EXP_1",
        type: "entry",
        entityType: "PARAMETER_DIES",
        dependencies: ["Select die"],
        description: "Enter the parameters for the die",
      },
      {
        id: "Select godet",
        collection: "/POLPRO_EQUIPMENT/EXTRUSION/EXTRUDER_EXP_4",
        type: "select",
        entityType: "GODETS",
        dependencies: [],
        description: "Select the godet",
      },
      {
        id: "Godet parameter",
        collection: "/POLPRO_RUDOLF.HUFENUS_AT_EMPA.CH/TEST/TEST_EXP_1",
        type: "entry",
        entityType: "PARAMETER_GODET",
        dependencies: ["Select godet"],
        description: "Enter the parameters for the die",
      },
      {
        id: "Select winder",
        collection: "/POLPRO_EQUIPMENT/EXTRUSION/EXTRUDER_EXP_10",
        type: "select",
        entityType: "WINDERS",
        dependencies: [],
        description: "Select the winder",
      },
      {
        id: "Winder parameter",
        collection: "/POLPRO_RUDOLF.HUFENUS_AT_EMPA.CH/TEST/TEST_EXP_1",
        type: "entry",
        entityType: "PARAMETER_WINDER",
        dependencies: ["Select winder"],
        description: "Enter the parameters for the winder",
      },
      {
        id: "Create fiber",
        collection: "/POLPRO_RUDOLF.HUFENUS_AT_EMPA.CH/TEST/TEST_EXP_1",
        type: "entry",
        entityType: "EXPERIMENTAL_STEP",
        dependencies: [
          "Extruder Parameter",
          "Spin pack parameter",
          "Die parameter",
          "Godet parameter",
          "Winder parameter"
        ],
        description: "Create the fiber",
      }
    ],
    "Create fiber",
    "Create fiber",
  );